import Projects from "@/components/layout/projects/Projects";
import ProjectsFilters from "@/components/layout/projects/ProjectsFilters";
import { AppSidebar } from "@/components/layout/sidebar/AppSideBar";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { auth, prisma } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "DevScope | Projects",
  description: "Generated by create next app",
};

interface PageProps {
  searchParams: {
    page?: string;
    language?: string;
    type?: string;
    sort?: string;
    year?: string;
  };
}

const page = async ({
  searchParams,
}: {
  searchParams: Promise<PageProps["searchParams"]>;
}) => {
  const session = await auth.api.getSession({ headers: await headers() });
  // console.log("Dashboard Page", session)
  if (session == null) return redirect("/auth/login");

  const resolvedSearchParams = await searchParams;

  const pageNumber = Number(resolvedSearchParams.page ?? 1);
  const language = resolvedSearchParams.language ?? "all";
  const type = resolvedSearchParams.type ?? "all";
  const sort = resolvedSearchParams.sort ?? "updated_desc";
  const year = resolvedSearchParams.year ?? "all";

  const githubProfile = await prisma.githubProfile.findUnique({
    where: { userId: session.user.id },
  });

  const latestSync = await prisma.githubSync.findUnique({
    where: { userId: session.user.id },
  });

  // Fetch distinct languages for this user
  const languageResults = await prisma.githubRepo.findMany({
    where: { userId: session.user.id },
    distinct: ["language"],
    select: { language: true },
  });

  // Fetch all repo pushedAt dates for this user
  const repoDates = await prisma.githubRepo.findMany({
    where: { userId: session.user.id },
    select: { pushedAt: true },
    orderBy: { pushedAt: "asc" }, // earliest first
  });

  let minYear = new Date().getFullYear();
  let maxYear = new Date().getFullYear();

  if (repoDates.length > 0) {
    minYear = repoDates[0].pushedAt.getFullYear();
    maxYear = repoDates[repoDates.length - 1].pushedAt.getFullYear();
  }

  // Create descending list of years
  const years = Array.from({ length: maxYear - minYear + 1 }, (_, i) =>
    (maxYear - i).toString(),
  );

  // Clean + remove null values
  const languages = languageResults
    .map((item) => item.language)
    .filter((lang): lang is string => Boolean(lang))
    .sort();

  return (
    <div>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar
          variant="inset"
          githubProfile={
            githubProfile
              ? {
                  profileUrl: githubProfile.profileUrl,
                  username: githubProfile.username,
                  avatarUrl: githubProfile.avatarUrl,
                }
              : null
          }
        />
        <SidebarInset>
          <SiteHeader
            title="Projects"
            githubProfile={
              githubProfile
                ? {
                    profileUrl: githubProfile.profileUrl,
                    username: githubProfile.username,
                    avatarUrl: githubProfile.avatarUrl,
                  }
                : null
            }
            latestSync={latestSync?.syncedAt ?? null}
          />
          <div className="flex flex-1 flex-col">
            <div className="@container/main flex flex-1 flex-col gap-2">
              <div className="flex flex-col gap-4 p-4 md:gap-6 md:py-6">
                <ProjectsFilters
                  currentLanguage={language}
                  currentType={type}
                  currentSort={sort}
                  currentYear={year}
                  languages={languages}
                  years={years}
                />
                <Projects
                  userId={session.user.id}
                  page={pageNumber}
                  language={language}
                  type={type}
                  sort={sort}
                  year={year}
                />
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
};

export default page;
