import ApplicationsTracker from "@/components/layout/job-applications/ApplicationsTracker";
import { AppSidebar } from "@/components/layout/sidebar/AppSideBar";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { auth, prisma } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "DevScope | Job Applications",
  description: "Generated by create next app",
};

const page = async () => {
  const session = await auth.api.getSession({ headers: await headers() });
  // console.log("Dashboard Page", session)
  if (session == null) return redirect("/auth/login");

  const githubProfile = await prisma.githubProfile.findUnique({
    where: { userId: session.user.id },
  });

  const sync = await prisma.githubSync.findUnique({
    where: { userId: session.user.id },
  });

  if (!sync) {
    const githubAccount = await prisma.account.findFirst({
      where: { userId: session.user.id, providerId: "github" },
    });

    if (githubAccount?.accessToken) {
      await fetch(`${process.env.BETTER_AUTH_URL}/api/github/sync`, {
        method: "POST",
        headers: {
          Cookie: (await headers()).get("cookie") ?? "",
        },
      });
    }
  }

  const latestSync = await prisma.githubSync.findUnique({
    where: { userId: session.user.id },
  });

  return (
    <div>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar
          variant="inset"
          githubProfile={
            githubProfile
              ? {
                  profileUrl: githubProfile.profileUrl,
                  username: githubProfile.username,
                  avatarUrl: githubProfile.avatarUrl,
                }
              : null
          }
        />
        <SidebarInset>
          <SiteHeader
            title="Job Applications"
            githubProfile={
              githubProfile
                ? {
                    profileUrl: githubProfile.profileUrl,
                    username: githubProfile.username,
                    avatarUrl: githubProfile.avatarUrl,
                  }
                : null
            }
            latestSync={latestSync?.syncedAt ?? null}
          />
          <div className="flex flex-1 flex-col">
            <div className="@container/main flex flex-1 flex-col gap-2">
              <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
                <ApplicationsTracker />
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
};

export default page;
