import { AppSidebar } from "@/components/layout/sidebar/AppSideBar";
import { CommitsCard } from "@/components/layout/dashboard/CommitsCard";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { auth, prisma } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import ApplicationsTracker from "@/components/layout/job-applications/ApplicationsTracker";
import { SectionCards } from "@/components/layout/dashboard/SectionCards";
import { startOfMonth } from "date-fns";

export const metadata: Metadata = {
  title: "DevScope | Dashboard",
  description: "Generated by create next app",
};

const page = async () => {
  const session = await auth.api.getSession({ headers: await headers() });
  // console.log("Dashboard Page", session)
  if (session == null) return redirect("/auth/login");

  const githubProfile = await prisma.githubProfile.findUnique({
    where: { userId: session.user.id },
  });

  const userId = session.user.id;
  const startOfCurrentMonth = startOfMonth(new Date());

  const [
    totalApplications,
    applicationsThisMonth,
    interviews,
    offers,
    rejected,
    active,
    resumeCount,
    repos,
  ] = await Promise.all([
    prisma.jobApplication.count({
      where: { userId },
    }),
    prisma.jobApplication.count({
      where: {
        userId,
        dateApplied: {
          gte: startOfCurrentMonth,
        },
      },
    }),
    prisma.jobApplication.count({
      where: { userId, status: "INTERVIEW" },
    }),
    prisma.jobApplication.count({
      where: { userId, status: "OFFER" },
    }),
    prisma.jobApplication.count({
      where: { userId, status: "REJECTED" },
    }),
    prisma.jobApplication.count({
      where: {
        userId,
        status: {
          in: ["APPLIED", "INTERVIEW"],
        },
      },
    }),
    prisma.resume.count({
      where: { userId },
    }),
    prisma.githubRepo.findMany({
      where: { userId },
      select: { stars: true },
    }),
  ]);

  const totalStars = repos.reduce((acc, repo) => acc + repo.stars, 0);

  const interviewRate =
    totalApplications === 0
      ? 0
      : Math.round((interviews / totalApplications) * 100);

  return (
    <div>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar
          variant="inset"
          githubProfile={
            githubProfile
              ? {
                  profileUrl: githubProfile.profileUrl,
                  username: githubProfile.username,
                  avatarUrl: githubProfile.avatarUrl,
                }
              : null
          }
        />
        <SidebarInset>
          <SiteHeader
            title="Dashboard"
            githubProfile={
              githubProfile
                ? {
                    profileUrl: githubProfile.profileUrl,
                    username: githubProfile.username,
                    avatarUrl: githubProfile.avatarUrl,
                  }
                : null
            }
            latestSync={null}
          />
          <div className="flex flex-1 flex-col">
            <div className="@container/main flex flex-1 flex-col gap-2">
              <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
                <SectionCards
                  stats={{
                    totalApplications,
                    applicationsThisMonth,
                    interviews,
                    offers,
                    rejected,
                    active,
                    resumeCount,
                    totalStars,
                    interviewRate,
                  }}
                />

                <CommitsCard />
                {/* <ChartAreaInteractive /> */}
                <ApplicationsTracker />
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
};

export default page;
