import SyncGithubButton from "@/components/github/SyncGithubButton";
import { AppSidebar } from "@/components/layout/sidebar/AppSideBar";
import { ChartAreaInteractive } from "@/components/layout/dashboard/ChatAreaInteractive";
import { CommitsCard } from "@/components/layout/dashboard/CommitsCard";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { auth, prisma } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import ApplicationsTracker from "@/components/layout/dashboard/ApplicationsTracker";

export const metadata: Metadata = {
  title: "DevScope Dashboard",
  description: "Generated by create next app",
};

const page = async () => {
  const session = await auth.api.getSession({ headers: await headers() });
  // console.log("Dashboard Page", session)
  if (session == null) return redirect("/auth/login");

  const githubProfile = await prisma.githubProfile.findUnique({
    where: { userId: session.user.id },
  });

  const sync = await prisma.githubSync.findUnique({
    where: { userId: session.user.id },
  });

  if (!sync) {
    const githubAccount = await prisma.account.findFirst({
      where: { userId: session.user.id, providerId: "github" },
    });

    if (githubAccount?.accessToken) {
      await fetch(`${process.env.BETTER_AUTH_URL}/api/github/sync`, {
        method: "POST",
        headers: {
          Cookie: (await headers()).get("cookie") ?? "",
        },
      });
    }
  }

  // const repos = await prisma.githubRepo.findMany({
  //   where: { userId: session.user.id },
  //   orderBy: { pushedAt: "desc" },
  // });

  const latestSync = await prisma.githubSync.findUnique({
    where: { userId: session.user.id },
  });

  return (
    <div>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar
          variant="inset"
          githubProfile={
            githubProfile
              ? {
                  profileUrl: githubProfile.profileUrl,
                  username: githubProfile.username,
                  avatarUrl: githubProfile.avatarUrl,
                }
              : null
          }
        />
        <SidebarInset>
          <SiteHeader
            title="Dashboard"
            githubProfile={
              githubProfile
                ? {
                    profileUrl: githubProfile.profileUrl,
                    username: githubProfile.username,
                    avatarUrl: githubProfile.avatarUrl,
                  }
                : null
            }
            latestSync={latestSync?.syncedAt ?? null}
          />
          <div className="flex flex-1 flex-col">
            <div className="@container/main flex flex-1 flex-col gap-2">
              <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
                <CommitsCard />
                {/* <div className="px-4 lg:px-6"> */}
                {/* <ChartAreaInteractive /> */}
                {/* </div> */}
                {/* Table here */}
                <ApplicationsTracker />
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
      {/* <div className="flex items-center justify-end gap-4 p-4 border rounded-md">
        <p className="text-sm text-muted-foreground">
          Last synced:{" "}
          {latestSync ? latestSync.syncedAt.toLocaleString() : "Never"}
        </p>

        <SyncGithubButton />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
        {repos.map((repo) => (
          <div key={repo.id} className="border rounded-md p-4">
            <h3 className="font-semibold">{repo.name}</h3>
            <p className="text-sm text-muted-foreground">
              ⭐ {repo.stars} · 🍴 {repo.forks}
            </p>
          </div>
        ))}
      </div> */}
    </div>
  );
};

export default page;
