import ResumeList from "@/components/layout/resumes/ResumeList";
import ResumeUploader from "@/components/layout/resumes/ResumeUploader";
import { AppSidebar } from "@/components/layout/sidebar/AppSideBar";
import { SiteHeader } from "@/components/layout/SiteHeader";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { auth, prisma } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "DevScope | Resumes",
  description: "Generated by create next app",
};

const page = async ({
  searchParams,
}: {
  searchParams: Promise<{ page?: string }>;
}) => {
  const session = await auth.api.getSession({ headers: await headers() });
  // console.log("Dashboard Page", session)
  if (session == null) return redirect("/auth/login");

  const githubProfile = await prisma.githubProfile.findUnique({
    where: { userId: session.user.id },
  });

  const params = await searchParams;
  const page = Number(params?.page) || 1;

  return (
    <div>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <AppSidebar
          variant="inset"
          githubProfile={
            githubProfile
              ? {
                  profileUrl: githubProfile.profileUrl,
                  username: githubProfile.username,
                  avatarUrl: githubProfile.avatarUrl,
                }
              : null
          }
        />
        <SidebarInset>
          <SiteHeader
            title="Resumes"
            githubProfile={
              githubProfile
                ? {
                    profileUrl: githubProfile.profileUrl,
                    username: githubProfile.username,
                    avatarUrl: githubProfile.avatarUrl,
                  }
                : null
            }
            latestSync={null}
          />
          <div className="flex flex-1 flex-col">
            <div className="@container/main flex flex-1 flex-col gap-2">
              <div className="flex flex-col gap-4 p-4 md:gap-6 md:py-6">
                <ResumeUploader />
                <Suspense fallback={<div>Loading resumes...</div>}>
                  <ResumeList userId={session.user.id} page={page} />
                </Suspense>
              </div>
            </div>
          </div>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
};

export default page;
